sudo: required
env:
  global:
  # DOCKER_PASSWORD
  - secure: "wu/fIOi7F+Yyx/VjyWgmWWDsyTUWbHH2A1OT8w9j0WqS3K1aFYM4V+XYI3NwsgOBvbSOYon71pK9XIZpXLLWABVxa5K6UFTii0Lrj1D6E9Oe4jbmRUfOBppX2Iiznl0G5yvZ0tw4R6/4JJHAFN+xEPAs3sM7HdZ8ALXllRKmvQW72ZCtrnBPcknlMZdY5lAQHLPZ0vA294iLeSUKljuiDg1+Ng9mSAMQKXr4vBemMsnOJ60xcUXP69adzbO/MyhPFDgiOGXuV2nnY7G+ls2P6m0XwUK4AKBld12KbPuaTULXKeEKM5zKPHwoyUolyxskseiJfk90dEe8u2+ZnkneeDjBwacTy9NTzZNIBQD6DCA8yc973PI/be09haPh5hoKD+oCP2X2SrQ7gmBCqXubXqYKT/IMbfK+w/EceFzcDHeyj6fXbBd42HeOresa8x3eBk2EMiBcTQQRfg9DnqOzNf5DNLojWt5T/lfKXhlqa3dU0OnrDF8OxjndFAD7VeGLln04C8x4fQHBdPQtxxON78te2tDNz6PZOLk4Di7Dctoo6HQg21oQnapOWZ7hZbn06/InFBDnyL5CfW9lyKTVqy51N1flf8m0EGjgtQ3U1HA8+0gDqTwGXRs6T4vKx/mRsghppIM89TQu0pn8Q0kJd9LtgHX1XsoWX72QSvQOF38="
  - DOCKER_USERNAME: untangleengineering
  - GOPATH="${HOME}/go"
  - DIR="${GOPATH}/src/github.com/untangle"
  matrix:
  - TARGET=glibc TEST="grep -q GNU/Linux"
  - TARGET=musl TEST="grep -q -v GNU/Linux"
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- mkdir -p "$DIR"
- mv "$TRAVIS_BUILD_DIR" "${DIR}/packetd"
- cd "${DIR}/packetd"
script:
- docker-compose -f build/docker-compose.build.yml up --build ${TARGET}-local || travis_terminate 1
- test -f ./cmd/packetd/packetd && file ./cmd/packetd/packetd | $TEST
notifications:
  email: false
  slack:
    rooms:
      secure: HhKVxkCcDT6XDSjprcjuDXDXw404hJIHLM+05ywp3dolvi3+ENxW4cinsNXByZlRfvnaUyNC3gqvi6JDGC9WUb8hhGyWA8s5KBmhlUc6wJc7vM5z1/Z662Du8/Gd/49nyG8vJ9e1zlIbXJ0aG5xLUdXun1l0RsgmyHekaAKUDHYafMk/SI/VzrdcMh614gb15RWA/sXeGk5NtpSjusTysiSEO0SI7+m61S6JT0bTP/yJr5OSV5DH+Asp+jqe3kj0UDKz6dB99EfgcK3ZUF65emZ/PWngnwHCa5yshtAdlzgqGZYxsnaS53oDIVvRbZEKIgQoXnJDA5SkUiBgoI9qpVa0tHMh47LniaMazMGbxzb9/s8aK21pKaUQBj9W75P7xX6oiUphIex0XhW3Wz5XU7DafnHbfmcqdyzsdB9JBvBINkGWNlmf4Jx2uC1JoH1yLKySO3EPaxgjx0bB+uxCzgYHgVPlBglje7DENzdboUprfQNEv2HHrt5xNaU6lDpRtA/Q72TH8OWJRQ073p8MQ28OY58YVCXXl40p6ic2yvgB6JAfHQnYGSSXpbtInpJrQ+9VyTfIfUtoiXkLxL4wPnlLaWYJUsSmnCoNRJZUAVzXlzYYtFzX+RQlDLLP6R88MwTm2yDNiAJqaV/s6rtTW961A3iOqCKMGcJJzCgZgOg=
    on_success: change
    on_failure: always
